language: python # => 1
    python: # => 2
      - "3.7"
    env:
      - DJANGO=2.2.4 DB=sqlite
    install: # => 5
      - pip install -r requirements.txt
    script: # => 7
      - python3 manage.py runserver
