language:
- python
python:
- "3.7"
install:
- pip3 install -r requirements.txt
before_script:
- python manage.py migrate --no-input
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: 3f88bd02-07ea-4568-b4e5-ac696e3e1d8e
  app: rsoibal1
  on:
    repo: Egorbigboss/RSOI
